### PR TITLE
fixs warnings from upgrading to Julia 0.4-rc2

### PR DESCRIPTION
**Pull request by jeff-regier**
Hi Kyle/Mike -- This PR fixes all the warnings from Julia 0.4-rc2.
Best, Jeff

### CODE REVIEW

**Comment by jeff-regier** [comment]
Hi @kbarbary , I removed the unnecessary calls to `@compat`.

**Comment by kbarbary** [comment]
Looks good to me!

**Comment by jeff-regier** [comment]
HI @kbarbary , Would you tag a new version of WCSLIB.jl with this revision? Thanks!

**Comment by kbarbary** [comment]
will do.

**Pull request merged**
